version: "3.9"
cache-service-postgres-db:
    image: postgres:12-alpine
    restart: always
    container_name: cache-service-postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=cache_service